version: 2
updates:
  - package-ecosystem: "npm" # or "yarn" if you're using Yarn
    directory: "/" # Location of your package.json or dependencies file
    schedule:
      interval: "daily" # You can set this to "daily" or "monthly"
