name: Automatic Testing for Foundry  Web App
on:
  push:
    branches:
      - main # Workflow will be triggered whenever there is a push in main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests in "tests" folder
        run: npm run backend-test
      - name: Instrument the frontend code
        run: |
          cp -R public instrumented
          npx nyc instrument public instrumented
      - name: Run the frontend test cases
        run: |
          rm -rf .nyc_output
          npx nyc --nycrc-path .nycrc-frontend cypress run
