services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: ndstrzz/rms-docker-img:v3
    container_name: rms-docker-container
    ports:
      - "8000:5050" 
      #testingg
