apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
spec:
  replicas: 2 # specifies how many identical replicas (pods) of the application should
              # be maintained, in this case, 2, which means Kubernetes will ensure that two pods running
              # the specified container are always available
  selector:
    matchLabels:
      app: rms-docker-img
  template:
    metadata:
      labels:
        app: rms-docker-img
    spec:
      containers:
        - name: rms-container
          image: ndstrzz/rms-docker-img:latest
          ports:
            - containerPort: 5050 # specifies the port that the application listens on
