name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub repository
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3
      
    # Step 2: Setup Node.js environment
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    # Step 3: Remove existing node_modules folder
    - name: Remove existing node_modules folder from cloned project
      run: rm -rf /home/runner/work/DevopsAuto/DevopsAuto/node_modules/*

    # Step 4: Install dependencies
    - name: Install dependencies based on package.json
      run: npm install

    # Step 5: Ensure all binaries in node_modules/.bin are executable
    - name: Ensure binaries in node_modules/.bin are executable
      run: chmod +x ./node_modules/.bin/*

    # Step 6: Run backend tests with coverage
    - name: Run backend tests
      run: npx nyc --nycrc-path .nycrc-backend mocha

    # Step 7: Instrument frontend code for coverage (if needed)
    - name: Instrument frontend code
      run: cp -R public instrumented & npx nyc instrument public instrumented

    # Step 8: Run frontend tests with coverage
    - name: Run frontend tests
      run: rm -rf .nyc_output & npx nyc --nycrc-path .nycrc-frontend cypress run
