name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub repository
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3

    # Step 2: Setup Node.js environment
    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies
    - name: Install dependencies based on package.json
      run: npm install

    # Step 4: Grant execution permissions to node_modules binaries
    - name: Grant permissions for binaries
      run: chmod +x ./node_modules/.bin/*

    # Step 5: Install Cypress binary explicitly
    - name: Install Cypress binary
      run: npx cypress install

    # Step 6: Cache Cypress binary
    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-

    # Step 7: Run backend tests
    - name: Run backend tests
      run: npx nyc --nycrc-path .nycrc-backend mocha

    # Step 8: Instrument frontend code
    - name: Instrument frontend code
      run: npx nyc instrument ./public ./instrumented

    # Step 9: Run frontend tests using updated config
    - name: Run frontend tests
      run: npx cypress run --config-file cypress.config.js
