name: Automatic Testing for Resource Management Web App
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: List repository files
        run: ls -R

      - name: Install dependencies
        working-directory: foundry-store-mgmt # Adjust this if your project is nested
        run: npm install

      - name: Run backend tests
        working-directory: foundry-store-mgmt # Adjust this if your project is nested
        run: npm run backend-test
